package com.honeycakesin.constants;

public enum UserSignupStatus {

	SUCCESS, USER_EXISTS, MOBILE_NUMBER_EXISTS, EMAIL_EXISTS, UNKOWN_FAILURE, MOBILE_LINKED_WITH_OTHER_EMAIL, EMAIL_LINKED_WITH_OTHER_MOBILE
}
